[workspace]
resolver = "2"
members = [
    "crates/mic2_rs",
    "crates/pymic2",
    "crates/libmic2",
]
exclude = [
    "examples/rust/find",
]

[workspace.metadata.cross.target.aarch64-unknown-linux-gnu]
pre-build = [
    "./ci/setup-debian.sh"
]
