[target.aarch64-unknown-linux-gnu]
pre-build = [
    "echo YES I AM WORKIND",
    "./ci/setup-debian.sh",
    "exit 12345"
]

[target.armv7-unknown-linux-musleabihf]
pre-build = [
    "echo YES I AM WORKIND",
    "./ci/setup-debian.sh",
]
