[package]
name = "libmic2"
version = "0.1.0"
edition = "2021"

[lib]
name = "mic2"
crate-type = ["cdylib", "staticlib"]
doc = false

[build-dependencies]
cbindgen = "0.29.2"
path-clean = "1.0.1"
cc = "1.0.98"
cmake = "0.1.50"

[dependencies.mic2]
path = "../mic2_rs"
