name: Rust

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: sudo ./ci/setup-debian.sh
      - run: cargo clippy --all-features --all-targets

  test:
    strategy:
        fail-fast: true
        matrix:
          include:
            - target: x86_64-unknown-linux-gnu
              os: ubuntu-latest
              cargo: cargo
            - target: aarch64-unknown-linux-gnu
              os: ubuntu-latest
              cargo: cross
            - target: armv7-unknown-linux-musleabihf
              os: ubuntu-latest
              cargo: cross
            - target: x86_64-pc-windows-msvc
              os: windows-latest
              cargo: cargo
            - target: x86_64-pc-windows-gnu
              os: windows-latest
              cargo: cargo
    name: "test ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cross
        if: matrix.cargo == 'cross'
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      - run: sudo ./ci/setup-debian.sh
        if: matrix.os == 'ubuntu-latest'
      - run: sudo apt-get install musl-tools
        if: matrix.cargo == 'cargo' && contains(matrix.target, 'musl')
      - name: Test Rust and C packages
        run: |
          ${{ matrix.cargo }} test \
            --features _skip-hil-testing \
            --target ${{ matrix.target }} \
            --package mic2
          ${{ matrix.cargo }} test \
            --target ${{ matrix.target }} \
            --package libmic2
        shell: bash
        if: '!matrix.notest'
      - name: Test python package (native only)
        if: matrix.cargo == 'cargo'
        run: |
          ${{ matrix.cargo }} test
            --features _skip-hil-testing
            --target ${{ matrix.target }}
            --package mic2_python

  fmt:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
            components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
  
  doc:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: sudo ./ci/setup-debian.sh
      - run: cargo doc
